apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
  POSTGRES_USER: {{ .Values.postgresql.username }}    # Base64 encoded value of "admin" YWRtaW4=
  POSTGRES_PASSWORD: {{ .Values.postgresql.password }}  # Base64 encoded value of "admin123"  YWRtaW4xMjM=
stringData:
  POSTGRES_HOST: postgresql-service
  POSTGRES_PORT:  {{ quote .Values.postgresql.port }}
  POSTGRES_DB: {{ .Values.postgresql.db }} 