apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.name }}
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.username }}   
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.password }}  
  
  MONGO_USERNAME: {{ .Values.mongo.username }}   
  MONGO_PASSWORD: {{ .Values.mongo.password }}  

stringData:
  MONGO_HOST: mongodb-service
  MONGO_PORT:  {{ quote .Values.mongo.port }}
  MONGO_DB: {{ .Values.mongo.db }} 