apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
  POSTGRES_USER: YWRtaW4=    # Base64 encoded value of "admin" YWRtaW4=
  POSTGRES_PASSWORD: YWRtaW4xMjM=  # Base64 encoded value of "admin123"  YWRtaW4xMjM=
stringData:
  POSTGRES_HOST: postgresql
  POSTGRES_PORT:  "5432"
  POSTGRES_DB: "walletdb" # eshopdb