apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port:  {{ .Values.port }}
      targetPort:  {{ .Values.port }}