apiVersion: v1
kind: Service
metadata:
  name:  {{ printf "%s-service" .Values.service_name }}
spec:
  selector:
    app:  {{ .Values.service_name }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
