apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
data:
  MONGO_USERNAME: YWRtaW4=  # Base64 encoded value of "admin"
  MONGO_PASSWORD: YWRtaW4xMjM=  # Base64 encoded value of "admin123"
stringData:
  MONGO_HOST: mongodb-service.mongodb
  MONGO_PORT: "27017"
  MONGO_DB: eshopdb